# featuregraph-ingest-service-environment
AWSTemplateFormatVersion: 2010-09-09

Description: Creates an environment for the ingest service

Resources:
  # Create an SNS topic for incoming messages
  IncomingMessageSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: 'FeatureGraph Incoming Message Topic'
      TopicName: 'featuregraph-incoming'

Outputs:
  IncomingMessageSNSTopic:
    Description: Incoming Message Topic ARN
    Value: !Ref IncomingMessageSNSTopic
    Export:
      Name: FeatureGraphIncomingMessageSNSTopic
